sudo: false
dist: xenial
language: php

services:
  - mysql

php:
  - 7.3
  - 7.2
  - 7.1
  - 7.0
  - 5.6

env:
  - SLIM_VERSION=3.12.*
  - SLIM_VERSION=3.11.*
  - SLIM_VERSION=3.10.*
  - SLIM_VERSION=3.9.*
  - SLIM_VERSION=3.8.*
  - SLIM_VERSION=3.7.*
  - SLIM_VERSION=3.6.*
  - SLIM_VERSION=3.5.*
  - SLIM_VERSION=3.4.*

before_script:
  - travis_retry composer require "slim/slim:${SLIM_VERSION}"
  - mysql -e "CREATE DATABASE slim; GRANT ALL ON slim.* TO 'aimeos'@'localhost' IDENTIFIED BY 'aimeos'"
  - php vendor/aimeos/aimeos-core/setup.php --config=src/aimeos-default.php unittest unittest

script:
  - vendor/bin/phpunit

after_success:
  - php vendor/bin/coveralls -c .coveralls.yml

matrix:
  fast_finish: true
  allow_failures:
    - php: 5.6
